import pandas as pd
dsl = pd.Series([2, 4, 6, 6, 10])
ds2 = pd.Series([1, 3, 5, 7, 10])
print ("Seriesl:")
print (dsl)
print ("Series2:")
print (ds2)
print ("Compare the elements of the said Series:")
print ("Equals:")
print (dsl[dsl==ds2])
print ("Greater than:")
print (ds1[ds1 > ds2])
print ("Less than:")
print (dsl[dsl < ds2])
